[package]
name = "port-checker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.0", features = ["derive"] }
inquire = "0.6.2"
procfs = "0.15.1"
reqwest = { version = "0.11.18", features = ["blocking", "json"] }
serde_json = "1.0.96"
termimad = "0.20"
terminal_size = "0.2.6"
