[package]
name = "port-checker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
procfs = "0.15.1"
tabled = { version = "0.12.0", features = ["color"] } 
termimad = "0.20"
terminal_size = "0.2.6"
