name: Rust

on:
  push:
    paths-ignore:
      - "**/README.md"
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  rust_toolchain: stable

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    
    - name: Setup | Rust
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: ${{ env.rust_toolchain }}
        components: rustfmt, clippy, rust-src
        
    - name: Setup | Checkout
      uses: actions/checkout@v4

    - name: Build | Fmt Check
      run: cargo fmt -- --check

    - name: Build | Clippy
      run: cargo clippy --no-deps -- -Dwarnings

    - name: Build | Compile
      run: cargo build --verbose
      
    - name: Test | Test
      run: cargo test --verbose
